# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tasks_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='taks',
            new_name='task',
        ),
    ]
