# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20170102_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(),
        ),
    ]
