# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20170108_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.DateTimeField(),
        ),
    ]
