# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20170111_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='alarm',
            field=models.BooleanField(default=False),
        ),
    ]
