# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170108_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='presents',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cooking',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cooking',
            name='procedure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='stuff',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='pack',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='mails',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='work',
            name='workers',
            field=models.TextField(blank=True),
        ),
    ]
